version: "3.9"

services:
  celery-worker:
    build:
      context: .
      dockerfile: celery_worker/Dockerfile
    container_name: celery_worker
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [ gpu ]
    env_file:
      - ".env"
    network_mode: host
    restart: always
    volumes:
      - "/stor:/stor"
    command: >
      sh -c "celery --app celery_worker.worker.worker.celery worker --concurrency=2 --pool=threads &
             celery --app celery_worker.worker.start.celery flower --port=${CELERY_FLOWER_PORT} &
             python celery_worker/hook/start.py"

  communicator:
    build:
      context: .
      dockerfile: communicator/Dockerfile
    container_name: communicator
    volumes:
      - "/stor:/stor"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ".env"
    network_mode: host
    restart: always
    command: >
      sh -c "python communicator/main.py"