version: "3.9"

services:
  celery-worker:
    build:
      context: .
      dockerfile: celery_worker/Dockerfile
    container_name: call-quality-worker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    env_file:
      - ".env"
    environment:
      - C_FORCE_ROOT=true
    network_mode: host
    restart: always
    volumes:
      - "/stor:/stor"
    command: >
      sh -c "celery --app celery_worker.worker.worker.celery worker --concurrency=1 --pool=threads --queues=scribe_v1_queue -E --hostname=worker1@%h &
             celery --app celery_worker.worker.worker.celery worker --concurrency=1 --pool=threads --queues=openai_whisper_queue -E --hostname=worker2@%h &
             celery --app celery_worker.worker.worker.celery worker --concurrency=1 --pool=threads --queues=gemini_queue -E --hostname=worker3@%h &
             python celery_worker/hook/start.py"

  communicator:
    build:
      context: .
      dockerfile: communicator/Dockerfile
    container_name: call-quality
    volumes:
      - "/stor:/stor"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ".env"
    network_mode: host
    depends_on:
      - celery-worker
    restart: always
    command: >
      sh -c "python communicator/main.py"